// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.21.2
// source: protobuf/ligolo.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_ligolo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ligolo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_protobuf_ligolo_proto_rawDescGZIP(), []int{0}
}

type Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Object []byte `protobuf:"bytes,1,opt,name=Object,proto3" json:"Object,omitempty"`
	Reason string `protobuf:"bytes,2,opt,name=Reason,proto3" json:"Reason,omitempty"`
}

func (x *Error) Reset() {
	*x = Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_ligolo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ligolo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_protobuf_ligolo_proto_rawDescGZIP(), []int{1}
}

func (x *Error) GetObject() []byte {
	if x != nil {
		return x.Object
	}
	return nil
}

func (x *Error) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type Event struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type  string `protobuf:"bytes,1,opt,name=Type,proto3" json:"Type,omitempty"`
	Data  []byte `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	Error string `protobuf:"bytes,3,opt,name=Error,proto3" json:"Error,omitempty"`
}

func (x *Event) Reset() {
	*x = Event{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_ligolo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ligolo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_protobuf_ligolo_proto_rawDescGZIP(), []int{2}
}

func (x *Event) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Event) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Event) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Agent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Alias    string   `protobuf:"bytes,1,opt,name=Alias,proto3" json:"Alias,omitempty"`
	Hostname string   `protobuf:"bytes,2,opt,name=Hostname,proto3" json:"Hostname,omitempty"`
	IPs      []string `protobuf:"bytes,3,rep,name=IPs,proto3" json:"IPs,omitempty"`
	Tun      *Tun     `protobuf:"bytes,4,opt,name=Tun,proto3" json:"Tun,omitempty"`
}

func (x *Agent) Reset() {
	*x = Agent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_ligolo_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Agent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Agent) ProtoMessage() {}

func (x *Agent) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ligolo_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Agent.ProtoReflect.Descriptor instead.
func (*Agent) Descriptor() ([]byte, []int) {
	return file_protobuf_ligolo_proto_rawDescGZIP(), []int{3}
}

func (x *Agent) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *Agent) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Agent) GetIPs() []string {
	if x != nil {
		return x.IPs
	}
	return nil
}

func (x *Agent) GetTun() *Tun {
	if x != nil {
		return x.Tun
	}
	return nil
}

type Tun struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Alias      string   `protobuf:"bytes,1,opt,name=Alias,proto3" json:"Alias,omitempty"`
	Routes     []*Route `protobuf:"bytes,2,rep,name=Routes,proto3" json:"Routes,omitempty"`
	IsLoopback bool     `protobuf:"varint,3,opt,name=IsLoopback,proto3" json:"IsLoopback,omitempty"`
}

func (x *Tun) Reset() {
	*x = Tun{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_ligolo_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tun) ProtoMessage() {}

func (x *Tun) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ligolo_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tun.ProtoReflect.Descriptor instead.
func (*Tun) Descriptor() ([]byte, []int) {
	return file_protobuf_ligolo_proto_rawDescGZIP(), []int{4}
}

func (x *Tun) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *Tun) GetRoutes() []*Route {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *Tun) GetIsLoopback() bool {
	if x != nil {
		return x.IsLoopback
	}
	return false
}

type Route struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cidr string `protobuf:"bytes,1,opt,name=Cidr,proto3" json:"Cidr,omitempty"`
}

func (x *Route) Reset() {
	*x = Route{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_ligolo_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ligolo_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_protobuf_ligolo_proto_rawDescGZIP(), []int{5}
}

func (x *Route) GetCidr() string {
	if x != nil {
		return x.Cidr
	}
	return ""
}

type TunRoute struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tun   *Tun   `protobuf:"bytes,1,opt,name=Tun,proto3" json:"Tun,omitempty"`
	Route *Route `protobuf:"bytes,2,opt,name=Route,proto3" json:"Route,omitempty"`
}

func (x *TunRoute) Reset() {
	*x = TunRoute{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_ligolo_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TunRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunRoute) ProtoMessage() {}

func (x *TunRoute) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ligolo_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunRoute.ProtoReflect.Descriptor instead.
func (*TunRoute) Descriptor() ([]byte, []int) {
	return file_protobuf_ligolo_proto_rawDescGZIP(), []int{6}
}

func (x *TunRoute) GetTun() *Tun {
	if x != nil {
		return x.Tun
	}
	return nil
}

func (x *TunRoute) GetRoute() *Route {
	if x != nil {
		return x.Route
	}
	return nil
}

type NewTunReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	IsLoopback bool   `protobuf:"varint,2,opt,name=IsLoopback,proto3" json:"IsLoopback,omitempty"`
}

func (x *NewTunReq) Reset() {
	*x = NewTunReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_ligolo_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewTunReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewTunReq) ProtoMessage() {}

func (x *NewTunReq) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ligolo_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewTunReq.ProtoReflect.Descriptor instead.
func (*NewTunReq) Descriptor() ([]byte, []int) {
	return file_protobuf_ligolo_proto_rawDescGZIP(), []int{7}
}

func (x *NewTunReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NewTunReq) GetIsLoopback() bool {
	if x != nil {
		return x.IsLoopback
	}
	return false
}

type Listener struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Agent *Agent `protobuf:"bytes,1,opt,name=Agent,proto3" json:"Agent,omitempty"`
	Alias string `protobuf:"bytes,2,opt,name=Alias,proto3" json:"Alias,omitempty"`
	From  string `protobuf:"bytes,3,opt,name=From,proto3" json:"From,omitempty"`
	To    string `protobuf:"bytes,4,opt,name=To,proto3" json:"To,omitempty"`
}

func (x *Listener) Reset() {
	*x = Listener{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_ligolo_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Listener) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Listener) ProtoMessage() {}

func (x *Listener) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ligolo_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Listener.ProtoReflect.Descriptor instead.
func (*Listener) Descriptor() ([]byte, []int) {
	return file_protobuf_ligolo_proto_rawDescGZIP(), []int{8}
}

func (x *Listener) GetAgent() *Agent {
	if x != nil {
		return x.Agent
	}
	return nil
}

func (x *Listener) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *Listener) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Listener) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type NewListenerReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentAlias string `protobuf:"bytes,1,opt,name=AgentAlias,proto3" json:"AgentAlias,omitempty"`
	Protocol   string `protobuf:"bytes,2,opt,name=Protocol,proto3" json:"Protocol,omitempty"`
	From       string `protobuf:"bytes,3,opt,name=From,proto3" json:"From,omitempty"`
	To         string `protobuf:"bytes,4,opt,name=To,proto3" json:"To,omitempty"`
}

func (x *NewListenerReq) Reset() {
	*x = NewListenerReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_ligolo_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewListenerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewListenerReq) ProtoMessage() {}

func (x *NewListenerReq) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ligolo_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewListenerReq.ProtoReflect.Descriptor instead.
func (*NewListenerReq) Descriptor() ([]byte, []int) {
	return file_protobuf_ligolo_proto_rawDescGZIP(), []int{9}
}

func (x *NewListenerReq) GetAgentAlias() string {
	if x != nil {
		return x.AgentAlias
	}
	return ""
}

func (x *NewListenerReq) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *NewListenerReq) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *NewListenerReq) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type DelListenerReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentAlias    string `protobuf:"bytes,1,opt,name=AgentAlias,proto3" json:"AgentAlias,omitempty"`
	ListenerAlias string `protobuf:"bytes,2,opt,name=ListenerAlias,proto3" json:"ListenerAlias,omitempty"`
}

func (x *DelListenerReq) Reset() {
	*x = DelListenerReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_ligolo_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelListenerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelListenerReq) ProtoMessage() {}

func (x *DelListenerReq) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ligolo_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelListenerReq.ProtoReflect.Descriptor instead.
func (*DelListenerReq) Descriptor() ([]byte, []int) {
	return file_protobuf_ligolo_proto_rawDescGZIP(), []int{10}
}

func (x *DelListenerReq) GetAgentAlias() string {
	if x != nil {
		return x.AgentAlias
	}
	return ""
}

func (x *DelListenerReq) GetListenerAlias() string {
	if x != nil {
		return x.ListenerAlias
	}
	return ""
}

type ListListenersResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Listeners []*Listener `protobuf:"bytes,1,rep,name=Listeners,proto3" json:"Listeners,omitempty"`
}

func (x *ListListenersResp) Reset() {
	*x = ListListenersResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_ligolo_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListListenersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListListenersResp) ProtoMessage() {}

func (x *ListListenersResp) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ligolo_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListListenersResp.ProtoReflect.Descriptor instead.
func (*ListListenersResp) Descriptor() ([]byte, []int) {
	return file_protobuf_ligolo_proto_rawDescGZIP(), []int{11}
}

func (x *ListListenersResp) GetListeners() []*Listener {
	if x != nil {
		return x.Listeners
	}
	return nil
}

type ListTunsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tuns []*Tun `protobuf:"bytes,1,rep,name=Tuns,proto3" json:"Tuns,omitempty"`
}

func (x *ListTunsResp) Reset() {
	*x = ListTunsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_ligolo_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTunsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTunsResp) ProtoMessage() {}

func (x *ListTunsResp) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ligolo_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTunsResp.ProtoReflect.Descriptor instead.
func (*ListTunsResp) Descriptor() ([]byte, []int) {
	return file_protobuf_ligolo_proto_rawDescGZIP(), []int{12}
}

func (x *ListTunsResp) GetTuns() []*Tun {
	if x != nil {
		return x.Tuns
	}
	return nil
}

type ListAgentsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Agents []*Agent `protobuf:"bytes,1,rep,name=Agents,proto3" json:"Agents,omitempty"`
}

func (x *ListAgentsResp) Reset() {
	*x = ListAgentsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_ligolo_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAgentsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsResp) ProtoMessage() {}

func (x *ListAgentsResp) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ligolo_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsResp.ProtoReflect.Descriptor instead.
func (*ListAgentsResp) Descriptor() ([]byte, []int) {
	return file_protobuf_ligolo_proto_rawDescGZIP(), []int{13}
}

func (x *ListAgentsResp) GetAgents() []*Agent {
	if x != nil {
		return x.Agents
	}
	return nil
}

type RelayStartReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentAlias string `protobuf:"bytes,1,opt,name=AgentAlias,proto3" json:"AgentAlias,omitempty"`
	TunAlias   string `protobuf:"bytes,2,opt,name=TunAlias,proto3" json:"TunAlias,omitempty"`
}

func (x *RelayStartReq) Reset() {
	*x = RelayStartReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_ligolo_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RelayStartReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayStartReq) ProtoMessage() {}

func (x *RelayStartReq) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ligolo_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayStartReq.ProtoReflect.Descriptor instead.
func (*RelayStartReq) Descriptor() ([]byte, []int) {
	return file_protobuf_ligolo_proto_rawDescGZIP(), []int{14}
}

func (x *RelayStartReq) GetAgentAlias() string {
	if x != nil {
		return x.AgentAlias
	}
	return ""
}

func (x *RelayStartReq) GetTunAlias() string {
	if x != nil {
		return x.TunAlias
	}
	return ""
}

type RelayStopReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentAlias string `protobuf:"bytes,1,opt,name=AgentAlias,proto3" json:"AgentAlias,omitempty"`
}

func (x *RelayStopReq) Reset() {
	*x = RelayStopReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_ligolo_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RelayStopReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayStopReq) ProtoMessage() {}

func (x *RelayStopReq) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ligolo_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayStopReq.ProtoReflect.Descriptor instead.
func (*RelayStopReq) Descriptor() ([]byte, []int) {
	return file_protobuf_ligolo_proto_rawDescGZIP(), []int{15}
}

func (x *RelayStopReq) GetAgentAlias() string {
	if x != nil {
		return x.AgentAlias
	}
	return ""
}

type Operator struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *Operator) Reset() {
	*x = Operator{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_ligolo_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Operator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operator) ProtoMessage() {}

func (x *Operator) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ligolo_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operator.ProtoReflect.Descriptor instead.
func (*Operator) Descriptor() ([]byte, []int) {
	return file_protobuf_ligolo_proto_rawDescGZIP(), []int{16}
}

func (x *Operator) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type NewRouteReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TunAlias string `protobuf:"bytes,1,opt,name=TunAlias,proto3" json:"TunAlias,omitempty"`
	Cidr     string `protobuf:"bytes,2,opt,name=Cidr,proto3" json:"Cidr,omitempty"`
	Force    bool   `protobuf:"varint,3,opt,name=Force,proto3" json:"Force,omitempty"`
}

func (x *NewRouteReq) Reset() {
	*x = NewRouteReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_ligolo_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewRouteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewRouteReq) ProtoMessage() {}

func (x *NewRouteReq) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ligolo_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewRouteReq.ProtoReflect.Descriptor instead.
func (*NewRouteReq) Descriptor() ([]byte, []int) {
	return file_protobuf_ligolo_proto_rawDescGZIP(), []int{17}
}

func (x *NewRouteReq) GetTunAlias() string {
	if x != nil {
		return x.TunAlias
	}
	return ""
}

func (x *NewRouteReq) GetCidr() string {
	if x != nil {
		return x.Cidr
	}
	return ""
}

func (x *NewRouteReq) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type NewRouteResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OverlappingTun *Tun `protobuf:"bytes,1,opt,name=OverlappingTun,proto3" json:"OverlappingTun,omitempty"`
}

func (x *NewRouteResp) Reset() {
	*x = NewRouteResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_ligolo_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewRouteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewRouteResp) ProtoMessage() {}

func (x *NewRouteResp) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ligolo_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewRouteResp.ProtoReflect.Descriptor instead.
func (*NewRouteResp) Descriptor() ([]byte, []int) {
	return file_protobuf_ligolo_proto_rawDescGZIP(), []int{18}
}

func (x *NewRouteResp) GetOverlappingTun() *Tun {
	if x != nil {
		return x.OverlappingTun
	}
	return nil
}

type DelRouteReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TunAlias string `protobuf:"bytes,1,opt,name=TunAlias,proto3" json:"TunAlias,omitempty"`
	Cidr     string `protobuf:"bytes,2,opt,name=Cidr,proto3" json:"Cidr,omitempty"`
}

func (x *DelRouteReq) Reset() {
	*x = DelRouteReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_ligolo_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelRouteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelRouteReq) ProtoMessage() {}

func (x *DelRouteReq) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ligolo_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelRouteReq.ProtoReflect.Descriptor instead.
func (*DelRouteReq) Descriptor() ([]byte, []int) {
	return file_protobuf_ligolo_proto_rawDescGZIP(), []int{19}
}

func (x *DelRouteReq) GetTunAlias() string {
	if x != nil {
		return x.TunAlias
	}
	return ""
}

func (x *DelRouteReq) GetCidr() string {
	if x != nil {
		return x.Cidr
	}
	return ""
}

type DelTunReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TunAlias string `protobuf:"bytes,1,opt,name=TunAlias,proto3" json:"TunAlias,omitempty"`
}

func (x *DelTunReq) Reset() {
	*x = DelTunReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_ligolo_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelTunReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelTunReq) ProtoMessage() {}

func (x *DelTunReq) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ligolo_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelTunReq.ProtoReflect.Descriptor instead.
func (*DelTunReq) Descriptor() ([]byte, []int) {
	return file_protobuf_ligolo_proto_rawDescGZIP(), []int{20}
}

func (x *DelTunReq) GetTunAlias() string {
	if x != nil {
		return x.TunAlias
	}
	return ""
}

type RenameTunReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OldAlias string `protobuf:"bytes,1,opt,name=OldAlias,proto3" json:"OldAlias,omitempty"`
	NewAlias string `protobuf:"bytes,2,opt,name=NewAlias,proto3" json:"NewAlias,omitempty"`
}

func (x *RenameTunReq) Reset() {
	*x = RenameTunReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_ligolo_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RenameTunReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameTunReq) ProtoMessage() {}

func (x *RenameTunReq) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ligolo_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameTunReq.ProtoReflect.Descriptor instead.
func (*RenameTunReq) Descriptor() ([]byte, []int) {
	return file_protobuf_ligolo_proto_rawDescGZIP(), []int{21}
}

func (x *RenameTunReq) GetOldAlias() string {
	if x != nil {
		return x.OldAlias
	}
	return ""
}

func (x *RenameTunReq) GetNewAlias() string {
	if x != nil {
		return x.NewAlias
	}
	return ""
}

type GenerateAgentReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Server      string `protobuf:"bytes,1,opt,name=Server,proto3" json:"Server,omitempty"`
	GOOS        string `protobuf:"bytes,2,opt,name=GOOS,proto3" json:"GOOS,omitempty"`
	GOARCH      string `protobuf:"bytes,3,opt,name=GOARCH,proto3" json:"GOARCH,omitempty"`
	Obfuscate   bool   `protobuf:"varint,4,opt,name=Obfuscate,proto3" json:"Obfuscate,omitempty"`
	SocksServer string `protobuf:"bytes,5,opt,name=SocksServer,proto3" json:"SocksServer,omitempty"`
	SocksUser   string `protobuf:"bytes,6,opt,name=SocksUser,proto3" json:"SocksUser,omitempty"`
	SocksPass   string `protobuf:"bytes,7,opt,name=SocksPass,proto3" json:"SocksPass,omitempty"`
}

func (x *GenerateAgentReq) Reset() {
	*x = GenerateAgentReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_ligolo_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateAgentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateAgentReq) ProtoMessage() {}

func (x *GenerateAgentReq) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ligolo_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateAgentReq.ProtoReflect.Descriptor instead.
func (*GenerateAgentReq) Descriptor() ([]byte, []int) {
	return file_protobuf_ligolo_proto_rawDescGZIP(), []int{22}
}

func (x *GenerateAgentReq) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *GenerateAgentReq) GetGOOS() string {
	if x != nil {
		return x.GOOS
	}
	return ""
}

func (x *GenerateAgentReq) GetGOARCH() string {
	if x != nil {
		return x.GOARCH
	}
	return ""
}

func (x *GenerateAgentReq) GetObfuscate() bool {
	if x != nil {
		return x.Obfuscate
	}
	return false
}

func (x *GenerateAgentReq) GetSocksServer() string {
	if x != nil {
		return x.SocksServer
	}
	return ""
}

func (x *GenerateAgentReq) GetSocksUser() string {
	if x != nil {
		return x.SocksUser
	}
	return ""
}

func (x *GenerateAgentReq) GetSocksPass() string {
	if x != nil {
		return x.SocksPass
	}
	return ""
}

type GenerateAgentResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentBinary []byte `protobuf:"bytes,1,opt,name=AgentBinary,proto3" json:"AgentBinary,omitempty"`
}

func (x *GenerateAgentResp) Reset() {
	*x = GenerateAgentResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_ligolo_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateAgentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateAgentResp) ProtoMessage() {}

func (x *GenerateAgentResp) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ligolo_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateAgentResp.ProtoReflect.Descriptor instead.
func (*GenerateAgentResp) Descriptor() ([]byte, []int) {
	return file_protobuf_ligolo_proto_rawDescGZIP(), []int{23}
}

func (x *GenerateAgentResp) GetAgentBinary() []byte {
	if x != nil {
		return x.AgentBinary
	}
	return nil
}

type RenameAgentReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OldAlias string `protobuf:"bytes,1,opt,name=OldAlias,proto3" json:"OldAlias,omitempty"`
	NewAlias string `protobuf:"bytes,2,opt,name=NewAlias,proto3" json:"NewAlias,omitempty"`
}

func (x *RenameAgentReq) Reset() {
	*x = RenameAgentReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_ligolo_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RenameAgentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameAgentReq) ProtoMessage() {}

func (x *RenameAgentReq) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ligolo_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameAgentReq.ProtoReflect.Descriptor instead.
func (*RenameAgentReq) Descriptor() ([]byte, []int) {
	return file_protobuf_ligolo_proto_rawDescGZIP(), []int{24}
}

func (x *RenameAgentReq) GetOldAlias() string {
	if x != nil {
		return x.OldAlias
	}
	return ""
}

func (x *RenameAgentReq) GetNewAlias() string {
	if x != nil {
		return x.NewAlias
	}
	return ""
}

type Cert struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	ExpiryDate string `protobuf:"bytes,2,opt,name=ExpiryDate,proto3" json:"ExpiryDate,omitempty"`
}

func (x *Cert) Reset() {
	*x = Cert{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_ligolo_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cert) ProtoMessage() {}

func (x *Cert) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ligolo_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cert.ProtoReflect.Descriptor instead.
func (*Cert) Descriptor() ([]byte, []int) {
	return file_protobuf_ligolo_proto_rawDescGZIP(), []int{25}
}

func (x *Cert) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Cert) GetExpiryDate() string {
	if x != nil {
		return x.ExpiryDate
	}
	return ""
}

type ListCertsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Certs []*Cert `protobuf:"bytes,1,rep,name=Certs,proto3" json:"Certs,omitempty"`
}

func (x *ListCertsResp) Reset() {
	*x = ListCertsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_ligolo_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCertsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCertsResp) ProtoMessage() {}

func (x *ListCertsResp) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ligolo_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCertsResp.ProtoReflect.Descriptor instead.
func (*ListCertsResp) Descriptor() ([]byte, []int) {
	return file_protobuf_ligolo_proto_rawDescGZIP(), []int{26}
}

func (x *ListCertsResp) GetCerts() []*Cert {
	if x != nil {
		return x.Certs
	}
	return nil
}

type RegenCertsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *RegenCertsReq) Reset() {
	*x = RegenCertsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_ligolo_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegenCertsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegenCertsReq) ProtoMessage() {}

func (x *RegenCertsReq) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ligolo_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegenCertsReq.ProtoReflect.Descriptor instead.
func (*RegenCertsReq) Descriptor() ([]byte, []int) {
	return file_protobuf_ligolo_proto_rawDescGZIP(), []int{27}
}

func (x *RegenCertsReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_protobuf_ligolo_proto protoreflect.FileDescriptor

var file_protobuf_ligolo_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x6c, 0x69, 0x67, 0x6f, 0x6c,
	0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6c, 0x69, 0x67, 0x6f, 0x6c, 0x6f, 0x22,
	0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x37, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x12, 0x16, 0x0a, 0x06, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x06, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x61,
	0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x65, 0x61, 0x73, 0x6f,
	0x6e, 0x22, 0x45, 0x0a, 0x05, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x6a, 0x0a, 0x05, 0x41, 0x67, 0x65, 0x6e,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x41, 0x6c, 0x69, 0x61, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x41, 0x6c, 0x69, 0x61, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x48, 0x6f, 0x73, 0x74, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x48, 0x6f, 0x73, 0x74, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x49, 0x50, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x03, 0x49, 0x50, 0x73, 0x12, 0x1d, 0x0a, 0x03, 0x54, 0x75, 0x6e, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x6c, 0x69, 0x67, 0x6f, 0x6c, 0x6f, 0x2e, 0x54, 0x75, 0x6e, 0x52,
	0x03, 0x54, 0x75, 0x6e, 0x22, 0x62, 0x0a, 0x03, 0x54, 0x75, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x41,
	0x6c, 0x69, 0x61, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x41, 0x6c, 0x69, 0x61,
	0x73, 0x12, 0x25, 0x0a, 0x06, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x6c, 0x69, 0x67, 0x6f, 0x6c, 0x6f, 0x2e, 0x52, 0x6f, 0x75, 0x74, 0x65,
	0x52, 0x06, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x49, 0x73, 0x4c, 0x6f,
	0x6f, 0x70, 0x62, 0x61, 0x63, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x49, 0x73,
	0x4c, 0x6f, 0x6f, 0x70, 0x62, 0x61, 0x63, 0x6b, 0x22, 0x1b, 0x0a, 0x05, 0x52, 0x6f, 0x75, 0x74,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x69, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x43, 0x69, 0x64, 0x72, 0x22, 0x4e, 0x0a, 0x08, 0x54, 0x75, 0x6e, 0x52, 0x6f, 0x75, 0x74,
	0x65, 0x12, 0x1d, 0x0a, 0x03, 0x54, 0x75, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b,
	0x2e, 0x6c, 0x69, 0x67, 0x6f, 0x6c, 0x6f, 0x2e, 0x54, 0x75, 0x6e, 0x52, 0x03, 0x54, 0x75, 0x6e,
	0x12, 0x23, 0x0a, 0x05, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0d, 0x2e, 0x6c, 0x69, 0x67, 0x6f, 0x6c, 0x6f, 0x2e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x05,
	0x52, 0x6f, 0x75, 0x74, 0x65, 0x22, 0x3f, 0x0a, 0x09, 0x4e, 0x65, 0x77, 0x54, 0x75, 0x6e, 0x52,
	0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x49, 0x73, 0x4c, 0x6f, 0x6f, 0x70,
	0x62, 0x61, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x49, 0x73, 0x4c, 0x6f,
	0x6f, 0x70, 0x62, 0x61, 0x63, 0x6b, 0x22, 0x69, 0x0a, 0x08, 0x4c, 0x69, 0x73, 0x74, 0x65, 0x6e,
	0x65, 0x72, 0x12, 0x23, 0x0a, 0x05, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x6c, 0x69, 0x67, 0x6f, 0x6c, 0x6f, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74,
	0x52, 0x05, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x41, 0x6c, 0x69, 0x61, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x41, 0x6c, 0x69, 0x61, 0x73, 0x12, 0x12, 0x0a,
	0x04, 0x46, 0x72, 0x6f, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x46, 0x72, 0x6f,
	0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x54, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x54,
	0x6f, 0x22, 0x70, 0x0a, 0x0e, 0x4e, 0x65, 0x77, 0x4c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x41, 0x6c, 0x69, 0x61,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x41, 0x6c,
	0x69, 0x61, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x12,
	0x12, 0x0a, 0x04, 0x46, 0x72, 0x6f, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x46,
	0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x54, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x54, 0x6f, 0x22, 0x56, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x65, 0x6e,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x41, 0x6c,
	0x69, 0x61, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x41, 0x67, 0x65, 0x6e, 0x74,
	0x41, 0x6c, 0x69, 0x61, 0x73, 0x12, 0x24, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x65,
	0x72, 0x41, 0x6c, 0x69, 0x61, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x4c, 0x69,
	0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x41, 0x6c, 0x69, 0x61, 0x73, 0x22, 0x43, 0x0a, 0x11, 0x4c,
	0x69, 0x73, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x2e, 0x0a, 0x09, 0x4c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6c, 0x69, 0x67, 0x6f, 0x6c, 0x6f, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x65, 0x6e, 0x65, 0x72, 0x52, 0x09, 0x4c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x73,
	0x22, 0x2f, 0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x75, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x1f, 0x0a, 0x04, 0x54, 0x75, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b,
	0x2e, 0x6c, 0x69, 0x67, 0x6f, 0x6c, 0x6f, 0x2e, 0x54, 0x75, 0x6e, 0x52, 0x04, 0x54, 0x75, 0x6e,
	0x73, 0x22, 0x37, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x25, 0x0a, 0x06, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6c, 0x69, 0x67, 0x6f, 0x6c, 0x6f, 0x2e, 0x41, 0x67, 0x65,
	0x6e, 0x74, 0x52, 0x06, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x4b, 0x0a, 0x0d, 0x52, 0x65,
	0x6c, 0x61, 0x79, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x41,
	0x67, 0x65, 0x6e, 0x74, 0x41, 0x6c, 0x69, 0x61, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x41, 0x6c, 0x69, 0x61, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x54,
	0x75, 0x6e, 0x41, 0x6c, 0x69, 0x61, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x54,
	0x75, 0x6e, 0x41, 0x6c, 0x69, 0x61, 0x73, 0x22, 0x2e, 0x0a, 0x0c, 0x52, 0x65, 0x6c, 0x61, 0x79,
	0x53, 0x74, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x41, 0x67, 0x65, 0x6e, 0x74,
	0x41, 0x6c, 0x69, 0x61, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x41, 0x67, 0x65,
	0x6e, 0x74, 0x41, 0x6c, 0x69, 0x61, 0x73, 0x22, 0x1e, 0x0a, 0x08, 0x4f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x53, 0x0a, 0x0b, 0x4e, 0x65, 0x77, 0x52, 0x6f,
	0x75, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x54, 0x75, 0x6e, 0x41, 0x6c, 0x69,
	0x61, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x54, 0x75, 0x6e, 0x41, 0x6c, 0x69,
	0x61, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x69, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x43, 0x69, 0x64, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x46, 0x6f, 0x72, 0x63, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x46, 0x6f, 0x72, 0x63, 0x65, 0x22, 0x43, 0x0a, 0x0c,
	0x4e, 0x65, 0x77, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x33, 0x0a, 0x0e,
	0x4f, 0x76, 0x65, 0x72, 0x6c, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x54, 0x75, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x6c, 0x69, 0x67, 0x6f, 0x6c, 0x6f, 0x2e, 0x54, 0x75,
	0x6e, 0x52, 0x0e, 0x4f, 0x76, 0x65, 0x72, 0x6c, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x54, 0x75,
	0x6e, 0x22, 0x3d, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x12, 0x1a, 0x0a, 0x08, 0x54, 0x75, 0x6e, 0x41, 0x6c, 0x69, 0x61, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x54, 0x75, 0x6e, 0x41, 0x6c, 0x69, 0x61, 0x73, 0x12, 0x12, 0x0a, 0x04,
	0x43, 0x69, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x43, 0x69, 0x64, 0x72,
	0x22, 0x27, 0x0a, 0x09, 0x44, 0x65, 0x6c, 0x54, 0x75, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a,
	0x08, 0x54, 0x75, 0x6e, 0x41, 0x6c, 0x69, 0x61, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x54, 0x75, 0x6e, 0x41, 0x6c, 0x69, 0x61, 0x73, 0x22, 0x46, 0x0a, 0x0c, 0x52, 0x65, 0x6e,
	0x61, 0x6d, 0x65, 0x54, 0x75, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x4f, 0x6c, 0x64,
	0x41, 0x6c, 0x69, 0x61, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4f, 0x6c, 0x64,
	0x41, 0x6c, 0x69, 0x61, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x4e, 0x65, 0x77, 0x41, 0x6c, 0x69, 0x61,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4e, 0x65, 0x77, 0x41, 0x6c, 0x69, 0x61,
	0x73, 0x22, 0xd2, 0x01, 0x0a, 0x10, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x41, 0x67,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x12,
	0x0a, 0x04, 0x47, 0x4f, 0x4f, 0x53, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x47, 0x4f,
	0x4f, 0x53, 0x12, 0x16, 0x0a, 0x06, 0x47, 0x4f, 0x41, 0x52, 0x43, 0x48, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x47, 0x4f, 0x41, 0x52, 0x43, 0x48, 0x12, 0x1c, 0x0a, 0x09, 0x4f, 0x62,
	0x66, 0x75, 0x73, 0x63, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x4f,
	0x62, 0x66, 0x75, 0x73, 0x63, 0x61, 0x74, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x53, 0x6f, 0x63, 0x6b,
	0x73, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x53,
	0x6f, 0x63, 0x6b, 0x73, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x6f,
	0x63, 0x6b, 0x73, 0x55, 0x73, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x53,
	0x6f, 0x63, 0x6b, 0x73, 0x55, 0x73, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x6f, 0x63, 0x6b,
	0x73, 0x50, 0x61, 0x73, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x53, 0x6f, 0x63,
	0x6b, 0x73, 0x50, 0x61, 0x73, 0x73, 0x22, 0x35, 0x0a, 0x11, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61,
	0x74, 0x65, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x20, 0x0a, 0x0b, 0x41,
	0x67, 0x65, 0x6e, 0x74, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x0b, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x22, 0x48, 0x0a,
	0x0e, 0x52, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x12,
	0x1a, 0x0a, 0x08, 0x4f, 0x6c, 0x64, 0x41, 0x6c, 0x69, 0x61, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x4f, 0x6c, 0x64, 0x41, 0x6c, 0x69, 0x61, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x4e,
	0x65, 0x77, 0x41, 0x6c, 0x69, 0x61, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4e,
	0x65, 0x77, 0x41, 0x6c, 0x69, 0x61, 0x73, 0x22, 0x3a, 0x0a, 0x04, 0x43, 0x65, 0x72, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x45, 0x78, 0x70, 0x69, 0x72, 0x79, 0x44, 0x61, 0x74,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x45, 0x78, 0x70, 0x69, 0x72, 0x79, 0x44,
	0x61, 0x74, 0x65, 0x22, 0x33, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x65, 0x72, 0x74, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x22, 0x0a, 0x05, 0x43, 0x65, 0x72, 0x74, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6c, 0x69, 0x67, 0x6f, 0x6c, 0x6f, 0x2e, 0x43, 0x65, 0x72,
	0x74, 0x52, 0x05, 0x43, 0x65, 0x72, 0x74, 0x73, 0x22, 0x23, 0x0a, 0x0d, 0x52, 0x65, 0x67, 0x65,
	0x6e, 0x43, 0x65, 0x72, 0x74, 0x73, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x32, 0x99, 0x07,
	0x0a, 0x06, 0x4c, 0x69, 0x67, 0x6f, 0x6c, 0x6f, 0x12, 0x28, 0x0a, 0x04, 0x4a, 0x6f, 0x69, 0x6e,
	0x12, 0x0d, 0x2e, 0x6c, 0x69, 0x67, 0x6f, 0x6c, 0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a,
	0x0d, 0x2e, 0x6c, 0x69, 0x67, 0x6f, 0x6c, 0x6f, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x22, 0x00,
	0x30, 0x01, 0x12, 0x35, 0x0a, 0x0a, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x73,
	0x12, 0x0d, 0x2e, 0x6c, 0x69, 0x67, 0x6f, 0x6c, 0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a,
	0x16, 0x2e, 0x6c, 0x69, 0x67, 0x6f, 0x6c, 0x6f, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x67, 0x65,
	0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x36, 0x0a, 0x0b, 0x52, 0x65, 0x6e,
	0x61, 0x6d, 0x65, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x2e, 0x6c, 0x69, 0x67, 0x6f, 0x6c,
	0x6f, 0x2e, 0x52, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71,
	0x1a, 0x0d, 0x2e, 0x6c, 0x69, 0x67, 0x6f, 0x6c, 0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22,
	0x00, 0x12, 0x2c, 0x0a, 0x06, 0x4e, 0x65, 0x77, 0x54, 0x75, 0x6e, 0x12, 0x11, 0x2e, 0x6c, 0x69,
	0x67, 0x6f, 0x6c, 0x6f, 0x2e, 0x4e, 0x65, 0x77, 0x54, 0x75, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x0d,
	0x2e, 0x6c, 0x69, 0x67, 0x6f, 0x6c, 0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12,
	0x2c, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x54, 0x75, 0x6e, 0x12, 0x11, 0x2e, 0x6c, 0x69, 0x67, 0x6f,
	0x6c, 0x6f, 0x2e, 0x44, 0x65, 0x6c, 0x54, 0x75, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x0d, 0x2e, 0x6c,
	0x69, 0x67, 0x6f, 0x6c, 0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x31, 0x0a,
	0x08, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x75, 0x6e, 0x73, 0x12, 0x0d, 0x2e, 0x6c, 0x69, 0x67, 0x6f,
	0x6c, 0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x14, 0x2e, 0x6c, 0x69, 0x67, 0x6f, 0x6c,
	0x6f, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x75, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00,
	0x12, 0x32, 0x0a, 0x09, 0x52, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x54, 0x75, 0x6e, 0x12, 0x14, 0x2e,
	0x6c, 0x69, 0x67, 0x6f, 0x6c, 0x6f, 0x2e, 0x52, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x54, 0x75, 0x6e,
	0x52, 0x65, 0x71, 0x1a, 0x0d, 0x2e, 0x6c, 0x69, 0x67, 0x6f, 0x6c, 0x6f, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x22, 0x00, 0x12, 0x37, 0x0a, 0x08, 0x4e, 0x65, 0x77, 0x52, 0x6f, 0x75, 0x74, 0x65,
	0x12, 0x13, 0x2e, 0x6c, 0x69, 0x67, 0x6f, 0x6c, 0x6f, 0x2e, 0x4e, 0x65, 0x77, 0x52, 0x6f, 0x75,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x6c, 0x69, 0x67, 0x6f, 0x6c, 0x6f, 0x2e, 0x4e,
	0x65, 0x77, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x30, 0x0a,
	0x08, 0x44, 0x65, 0x6c, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x12, 0x13, 0x2e, 0x6c, 0x69, 0x67, 0x6f,
	0x6c, 0x6f, 0x2e, 0x44, 0x65, 0x6c, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x0d,
	0x2e, 0x6c, 0x69, 0x67, 0x6f, 0x6c, 0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12,
	0x36, 0x0a, 0x0b, 0x4e, 0x65, 0x77, 0x4c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x12, 0x16,
	0x2e, 0x6c, 0x69, 0x67, 0x6f, 0x6c, 0x6f, 0x2e, 0x4e, 0x65, 0x77, 0x4c, 0x69, 0x73, 0x74, 0x65,
	0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x0d, 0x2e, 0x6c, 0x69, 0x67, 0x6f, 0x6c, 0x6f, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x36, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x4c, 0x69,
	0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x12, 0x16, 0x2e, 0x6c, 0x69, 0x67, 0x6f, 0x6c, 0x6f, 0x2e,
	0x44, 0x65, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x0d,
	0x2e, 0x6c, 0x69, 0x67, 0x6f, 0x6c, 0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12,
	0x3b, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x73,
	0x12, 0x0d, 0x2e, 0x6c, 0x69, 0x67, 0x6f, 0x6c, 0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a,
	0x19, 0x2e, 0x6c, 0x69, 0x67, 0x6f, 0x6c, 0x6f, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4c, 0x69, 0x73,
	0x74, 0x65, 0x6e, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x34, 0x0a, 0x0a,
	0x52, 0x65, 0x6c, 0x61, 0x79, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x15, 0x2e, 0x6c, 0x69, 0x67,
	0x6f, 0x6c, 0x6f, 0x2e, 0x52, 0x65, 0x6c, 0x61, 0x79, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65,
	0x71, 0x1a, 0x0d, 0x2e, 0x6c, 0x69, 0x67, 0x6f, 0x6c, 0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x22, 0x00, 0x12, 0x32, 0x0a, 0x09, 0x52, 0x65, 0x6c, 0x61, 0x79, 0x53, 0x74, 0x6f, 0x70, 0x12,
	0x14, 0x2e, 0x6c, 0x69, 0x67, 0x6f, 0x6c, 0x6f, 0x2e, 0x52, 0x65, 0x6c, 0x61, 0x79, 0x53, 0x74,
	0x6f, 0x70, 0x52, 0x65, 0x71, 0x1a, 0x0d, 0x2e, 0x6c, 0x69, 0x67, 0x6f, 0x6c, 0x6f, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x0d, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61,
	0x74, 0x65, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x12, 0x18, 0x2e, 0x6c, 0x69, 0x67, 0x6f, 0x6c, 0x6f,
	0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x1a, 0x19, 0x2e, 0x6c, 0x69, 0x67, 0x6f, 0x6c, 0x6f, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x74, 0x65, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x33,
	0x0a, 0x09, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x65, 0x72, 0x74, 0x73, 0x12, 0x0d, 0x2e, 0x6c, 0x69,
	0x67, 0x6f, 0x6c, 0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x15, 0x2e, 0x6c, 0x69, 0x67,
	0x6f, 0x6c, 0x6f, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x65, 0x72, 0x74, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x22, 0x00, 0x12, 0x34, 0x0a, 0x0a, 0x52, 0x65, 0x67, 0x65, 0x6e, 0x43, 0x65, 0x72, 0x74,
	0x73, 0x12, 0x15, 0x2e, 0x6c, 0x69, 0x67, 0x6f, 0x6c, 0x6f, 0x2e, 0x52, 0x65, 0x67, 0x65, 0x6e,
	0x43, 0x65, 0x72, 0x74, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x0d, 0x2e, 0x6c, 0x69, 0x67, 0x6f, 0x6c,
	0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x74, 0x70, 0x72, 0x65, 0x70, 0x6f, 0x72,
	0x74, 0x2f, 0x6c, 0x69, 0x67, 0x6f, 0x6c, 0x6f, 0x2d, 0x6d, 0x70, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuf_ligolo_proto_rawDescOnce sync.Once
	file_protobuf_ligolo_proto_rawDescData = file_protobuf_ligolo_proto_rawDesc
)

func file_protobuf_ligolo_proto_rawDescGZIP() []byte {
	file_protobuf_ligolo_proto_rawDescOnce.Do(func() {
		file_protobuf_ligolo_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_ligolo_proto_rawDescData)
	})
	return file_protobuf_ligolo_proto_rawDescData
}

var file_protobuf_ligolo_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_protobuf_ligolo_proto_goTypes = []interface{}{
	(*Empty)(nil),             // 0: ligolo.Empty
	(*Error)(nil),             // 1: ligolo.Error
	(*Event)(nil),             // 2: ligolo.Event
	(*Agent)(nil),             // 3: ligolo.Agent
	(*Tun)(nil),               // 4: ligolo.Tun
	(*Route)(nil),             // 5: ligolo.Route
	(*TunRoute)(nil),          // 6: ligolo.TunRoute
	(*NewTunReq)(nil),         // 7: ligolo.NewTunReq
	(*Listener)(nil),          // 8: ligolo.Listener
	(*NewListenerReq)(nil),    // 9: ligolo.NewListenerReq
	(*DelListenerReq)(nil),    // 10: ligolo.DelListenerReq
	(*ListListenersResp)(nil), // 11: ligolo.ListListenersResp
	(*ListTunsResp)(nil),      // 12: ligolo.ListTunsResp
	(*ListAgentsResp)(nil),    // 13: ligolo.ListAgentsResp
	(*RelayStartReq)(nil),     // 14: ligolo.RelayStartReq
	(*RelayStopReq)(nil),      // 15: ligolo.RelayStopReq
	(*Operator)(nil),          // 16: ligolo.Operator
	(*NewRouteReq)(nil),       // 17: ligolo.NewRouteReq
	(*NewRouteResp)(nil),      // 18: ligolo.NewRouteResp
	(*DelRouteReq)(nil),       // 19: ligolo.DelRouteReq
	(*DelTunReq)(nil),         // 20: ligolo.DelTunReq
	(*RenameTunReq)(nil),      // 21: ligolo.RenameTunReq
	(*GenerateAgentReq)(nil),  // 22: ligolo.GenerateAgentReq
	(*GenerateAgentResp)(nil), // 23: ligolo.GenerateAgentResp
	(*RenameAgentReq)(nil),    // 24: ligolo.RenameAgentReq
	(*Cert)(nil),              // 25: ligolo.Cert
	(*ListCertsResp)(nil),     // 26: ligolo.ListCertsResp
	(*RegenCertsReq)(nil),     // 27: ligolo.RegenCertsReq
}
var file_protobuf_ligolo_proto_depIdxs = []int32{
	4,  // 0: ligolo.Agent.Tun:type_name -> ligolo.Tun
	5,  // 1: ligolo.Tun.Routes:type_name -> ligolo.Route
	4,  // 2: ligolo.TunRoute.Tun:type_name -> ligolo.Tun
	5,  // 3: ligolo.TunRoute.Route:type_name -> ligolo.Route
	3,  // 4: ligolo.Listener.Agent:type_name -> ligolo.Agent
	8,  // 5: ligolo.ListListenersResp.Listeners:type_name -> ligolo.Listener
	4,  // 6: ligolo.ListTunsResp.Tuns:type_name -> ligolo.Tun
	3,  // 7: ligolo.ListAgentsResp.Agents:type_name -> ligolo.Agent
	4,  // 8: ligolo.NewRouteResp.OverlappingTun:type_name -> ligolo.Tun
	25, // 9: ligolo.ListCertsResp.Certs:type_name -> ligolo.Cert
	0,  // 10: ligolo.Ligolo.Join:input_type -> ligolo.Empty
	0,  // 11: ligolo.Ligolo.ListAgents:input_type -> ligolo.Empty
	24, // 12: ligolo.Ligolo.RenameAgent:input_type -> ligolo.RenameAgentReq
	7,  // 13: ligolo.Ligolo.NewTun:input_type -> ligolo.NewTunReq
	20, // 14: ligolo.Ligolo.DelTun:input_type -> ligolo.DelTunReq
	0,  // 15: ligolo.Ligolo.ListTuns:input_type -> ligolo.Empty
	21, // 16: ligolo.Ligolo.RenameTun:input_type -> ligolo.RenameTunReq
	17, // 17: ligolo.Ligolo.NewRoute:input_type -> ligolo.NewRouteReq
	19, // 18: ligolo.Ligolo.DelRoute:input_type -> ligolo.DelRouteReq
	9,  // 19: ligolo.Ligolo.NewListener:input_type -> ligolo.NewListenerReq
	10, // 20: ligolo.Ligolo.DelListener:input_type -> ligolo.DelListenerReq
	0,  // 21: ligolo.Ligolo.ListListeners:input_type -> ligolo.Empty
	14, // 22: ligolo.Ligolo.RelayStart:input_type -> ligolo.RelayStartReq
	15, // 23: ligolo.Ligolo.RelayStop:input_type -> ligolo.RelayStopReq
	22, // 24: ligolo.Ligolo.GenerateAgent:input_type -> ligolo.GenerateAgentReq
	0,  // 25: ligolo.Ligolo.ListCerts:input_type -> ligolo.Empty
	27, // 26: ligolo.Ligolo.RegenCerts:input_type -> ligolo.RegenCertsReq
	2,  // 27: ligolo.Ligolo.Join:output_type -> ligolo.Event
	13, // 28: ligolo.Ligolo.ListAgents:output_type -> ligolo.ListAgentsResp
	0,  // 29: ligolo.Ligolo.RenameAgent:output_type -> ligolo.Empty
	0,  // 30: ligolo.Ligolo.NewTun:output_type -> ligolo.Empty
	0,  // 31: ligolo.Ligolo.DelTun:output_type -> ligolo.Empty
	12, // 32: ligolo.Ligolo.ListTuns:output_type -> ligolo.ListTunsResp
	0,  // 33: ligolo.Ligolo.RenameTun:output_type -> ligolo.Empty
	18, // 34: ligolo.Ligolo.NewRoute:output_type -> ligolo.NewRouteResp
	0,  // 35: ligolo.Ligolo.DelRoute:output_type -> ligolo.Empty
	0,  // 36: ligolo.Ligolo.NewListener:output_type -> ligolo.Empty
	0,  // 37: ligolo.Ligolo.DelListener:output_type -> ligolo.Empty
	11, // 38: ligolo.Ligolo.ListListeners:output_type -> ligolo.ListListenersResp
	0,  // 39: ligolo.Ligolo.RelayStart:output_type -> ligolo.Empty
	0,  // 40: ligolo.Ligolo.RelayStop:output_type -> ligolo.Empty
	23, // 41: ligolo.Ligolo.GenerateAgent:output_type -> ligolo.GenerateAgentResp
	26, // 42: ligolo.Ligolo.ListCerts:output_type -> ligolo.ListCertsResp
	0,  // 43: ligolo.Ligolo.RegenCerts:output_type -> ligolo.Empty
	27, // [27:44] is the sub-list for method output_type
	10, // [10:27] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_protobuf_ligolo_proto_init() }
func file_protobuf_ligolo_proto_init() {
	if File_protobuf_ligolo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_ligolo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_ligolo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_ligolo_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Event); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_ligolo_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Agent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_ligolo_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tun); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_ligolo_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Route); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_ligolo_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TunRoute); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_ligolo_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewTunReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_ligolo_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Listener); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_ligolo_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewListenerReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_ligolo_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelListenerReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_ligolo_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListListenersResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_ligolo_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListTunsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_ligolo_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAgentsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_ligolo_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RelayStartReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_ligolo_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RelayStopReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_ligolo_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Operator); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_ligolo_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewRouteReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_ligolo_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewRouteResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_ligolo_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelRouteReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_ligolo_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelTunReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_ligolo_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RenameTunReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_ligolo_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateAgentReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_ligolo_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateAgentResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_ligolo_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RenameAgentReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_ligolo_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cert); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_ligolo_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListCertsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_ligolo_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegenCertsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_ligolo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuf_ligolo_proto_goTypes,
		DependencyIndexes: file_protobuf_ligolo_proto_depIdxs,
		MessageInfos:      file_protobuf_ligolo_proto_msgTypes,
	}.Build()
	File_protobuf_ligolo_proto = out.File
	file_protobuf_ligolo_proto_rawDesc = nil
	file_protobuf_ligolo_proto_goTypes = nil
	file_protobuf_ligolo_proto_depIdxs = nil
}
